id: P22EAED85
initial_creation_type: input
source_metadata:
  title: Peaceful and Wrathful Deities
  language: en
  description: 'Texts related to the forty-two peaceful and fifty-eight wrathful deities,
    known collectively as the zhitro (zhi khro):'
  volume:
    c16cf43521db4932b06578d42bb23745:
      title: In Praise of the Meaning of the Main Mantras of the Peaceful and Wrathful
        Deities
      parent: Mantra
    605937a5acef416094e17b93c823374a:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Sādhanas
created_at: '2022-03-01T05:03:07.343467'
last_modified_at: '2022-03-01T05:03:07.343474'
